pages = [{"l":"api/index.html","n":"API","t":" API","d":"api"},
{"l":"api/little/config.html","n":"little.config","t":"package little.config","d":"little/config"},
{"l":"api/little/config/ConfigDelegate.html","n":"ConfigDelegate","t":"trait ConfigDelegate[T]","d":"little/config/ConfigDelegate"},
{"l":"api/little/config/ConfigDelegate.html","n":"get","t":"def get(config: Config, path: String): T","d":"little/config/ConfigDelegate"},
{"l":"api/little/config/Implicits$.html","n":"Implicits","t":"object Implicits","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$stringDelegate$.html","n":"stringDelegate","t":"given stringDelegate: ConfigDelegate[String]","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$stringDelegate$.html","n":"get","t":"def get(config: Config, path: String): String","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$booleanDelegate$.html","n":"booleanDelegate","t":"given booleanDelegate: ConfigDelegate[Boolean]","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$booleanDelegate$.html","n":"get","t":"def get(config: Config, path: String): Boolean","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$intDelegate$.html","n":"intDelegate","t":"given intDelegate: ConfigDelegate[Int]","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$intDelegate$.html","n":"get","t":"def get(config: Config, path: String): Int","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$longDelegate$.html","n":"longDelegate","t":"given longDelegate: ConfigDelegate[Long]","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$longDelegate$.html","n":"get","t":"def get(config: Config, path: String): Long","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$doubleDelegate$.html","n":"doubleDelegate","t":"given doubleDelegate: ConfigDelegate[Double]","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$doubleDelegate$.html","n":"get","t":"def get(config: Config, path: String): Double","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$durationDelegate$.html","n":"durationDelegate","t":"given durationDelegate: ConfigDelegate[Duration]","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$durationDelegate$.html","n":"get","t":"def get(config: Config, path: String): Duration","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$periodDelegate$.html","n":"periodDelegate","t":"given periodDelegate: ConfigDelegate[Period]","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$periodDelegate$.html","n":"get","t":"def get(config: Config, path: String): Period","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$memorySizeDelegate$.html","n":"memorySizeDelegate","t":"given memorySizeDelegate: ConfigDelegate[ConfigMemorySize]","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$memorySizeDelegate$.html","n":"get","t":"def get(config: Config, path: String): ConfigMemorySize","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$configDelegate$.html","n":"configDelegate","t":"given configDelegate: ConfigDelegate[Config]","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$configDelegate$.html","n":"get","t":"def get(config: Config, path: String): Config","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$fileDelegate$.html","n":"fileDelegate","t":"given fileDelegate: ConfigDelegate[File]","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$fileDelegate$.html","n":"get","t":"def get(config: Config, path: String): File","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$.html","n":"collectionDelegate","t":"given collectionDelegate","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$.html","n":"enumDelegate","t":"given enumDelegate","d":"little/config/Implicits$"},
{"l":"api/little/config/Implicits$$stringDelegate$.html","n":"stringDelegate","t":"given stringDelegate: ConfigDelegate[String]","d":"little/config/Implicits$$stringDelegate$"},
{"l":"api/little/config/Implicits$$stringDelegate$.html","n":"get","t":"def get(config: Config, path: String): String","d":"little/config/Implicits$$stringDelegate$"},
{"l":"api/little/config/Implicits$$booleanDelegate$.html","n":"booleanDelegate","t":"given booleanDelegate: ConfigDelegate[Boolean]","d":"little/config/Implicits$$booleanDelegate$"},
{"l":"api/little/config/Implicits$$booleanDelegate$.html","n":"get","t":"def get(config: Config, path: String): Boolean","d":"little/config/Implicits$$booleanDelegate$"},
{"l":"api/little/config/Implicits$$intDelegate$.html","n":"intDelegate","t":"given intDelegate: ConfigDelegate[Int]","d":"little/config/Implicits$$intDelegate$"},
{"l":"api/little/config/Implicits$$intDelegate$.html","n":"get","t":"def get(config: Config, path: String): Int","d":"little/config/Implicits$$intDelegate$"},
{"l":"api/little/config/Implicits$$longDelegate$.html","n":"longDelegate","t":"given longDelegate: ConfigDelegate[Long]","d":"little/config/Implicits$$longDelegate$"},
{"l":"api/little/config/Implicits$$longDelegate$.html","n":"get","t":"def get(config: Config, path: String): Long","d":"little/config/Implicits$$longDelegate$"},
{"l":"api/little/config/Implicits$$doubleDelegate$.html","n":"doubleDelegate","t":"given doubleDelegate: ConfigDelegate[Double]","d":"little/config/Implicits$$doubleDelegate$"},
{"l":"api/little/config/Implicits$$doubleDelegate$.html","n":"get","t":"def get(config: Config, path: String): Double","d":"little/config/Implicits$$doubleDelegate$"},
{"l":"api/little/config/Implicits$$durationDelegate$.html","n":"durationDelegate","t":"given durationDelegate: ConfigDelegate[Duration]","d":"little/config/Implicits$$durationDelegate$"},
{"l":"api/little/config/Implicits$$durationDelegate$.html","n":"get","t":"def get(config: Config, path: String): Duration","d":"little/config/Implicits$$durationDelegate$"},
{"l":"api/little/config/Implicits$$periodDelegate$.html","n":"periodDelegate","t":"given periodDelegate: ConfigDelegate[Period]","d":"little/config/Implicits$$periodDelegate$"},
{"l":"api/little/config/Implicits$$periodDelegate$.html","n":"get","t":"def get(config: Config, path: String): Period","d":"little/config/Implicits$$periodDelegate$"},
{"l":"api/little/config/Implicits$$memorySizeDelegate$.html","n":"memorySizeDelegate","t":"given memorySizeDelegate: ConfigDelegate[ConfigMemorySize]","d":"little/config/Implicits$$memorySizeDelegate$"},
{"l":"api/little/config/Implicits$$memorySizeDelegate$.html","n":"get","t":"def get(config: Config, path: String): ConfigMemorySize","d":"little/config/Implicits$$memorySizeDelegate$"},
{"l":"api/little/config/Implicits$$configDelegate$.html","n":"configDelegate","t":"given configDelegate: ConfigDelegate[Config]","d":"little/config/Implicits$$configDelegate$"},
{"l":"api/little/config/Implicits$$configDelegate$.html","n":"get","t":"def get(config: Config, path: String): Config","d":"little/config/Implicits$$configDelegate$"},
{"l":"api/little/config/Implicits$$fileDelegate$.html","n":"fileDelegate","t":"given fileDelegate: ConfigDelegate[File]","d":"little/config/Implicits$$fileDelegate$"},
{"l":"api/little/config/Implicits$$fileDelegate$.html","n":"get","t":"def get(config: Config, path: String): File","d":"little/config/Implicits$$fileDelegate$"},
{"l":"api/little/config/Implicits$$ConfigType.html","n":"ConfigType","t":"class ConfigType(config: Config) extends AnyVal","d":"little/config/Implicits$$ConfigType"},
{"l":"api/little/config/Implicits$$ConfigType.html","n":"getFile","t":"def getFile(path: String): File","d":"little/config/Implicits$$ConfigType"},
{"l":"api/little/config/Implicits$$ConfigType.html","n":"getFileList","t":"def getFileList(path: String): List[File]","d":"little/config/Implicits$$ConfigType"},
{"l":"api/little/config/Implicits$$ConfigType.html","n":"get","t":"def get[T](path: String)(using delegate: ConfigDelegate[T]): T","d":"little/config/Implicits$$ConfigType"},
{"l":"api/little/config/Implicits$$ConfigType.html","n":"getOrElse","t":"def getOrElse[T](path: String, default: => T)(using delegate: ConfigDelegate[T]): T","d":"little/config/Implicits$$ConfigType"},
{"l":"api/little/config/Implicits$$ConfigType.html","n":"getOption","t":"def getOption[T](path: String)(using delegate: ConfigDelegate[T]): Option[T]","d":"little/config/Implicits$$ConfigType"},
{"l":"api/little/config/Implicits$$ConfigType.html","n":"getTry","t":"def getTry[T](path: String)(using delegate: ConfigDelegate[T]): Try[T]","d":"little/config/Implicits$$ConfigType"},
{"l":"api/index.html","n":"API","t":" API","d":"api"}];