pages = [{"l":"index.html","n":"little-config","t":"little-config","d":"","k":"static"},
{"l":"little/config.html","n":"little.config","t":"package little.config","d":"little/config","k":"package"},
{"l":"little/config.html","n":"ConfigMethods","t":"def ConfigMethods(config: Config): ConfigMethods","d":"little/config","k":"def"},
{"l":"little/config.html","n":"booleanDelegate","t":"given booleanDelegate: booleanDelegate.type","d":"little/config","k":"given"},
{"l":"little/config.html","n":"collectionDelegate","t":"given collectionDelegate[T, M[T]](using delegate: ConfigDelegate[T])(using factory: Factory[T, M[T]]): ConfigDelegate[M[T]]","d":"little/config","k":"given"},
{"l":"little/config.html","n":"configDelegate","t":"given configDelegate: configDelegate.type","d":"little/config","k":"given"},
{"l":"little/config.html","n":"doubleDelegate","t":"given doubleDelegate: doubleDelegate.type","d":"little/config","k":"given"},
{"l":"little/config.html","n":"durationDelegate","t":"given durationDelegate: durationDelegate.type","d":"little/config","k":"given"},
{"l":"little/config.html","n":"enumDelegate","t":"given enumDelegate[T <: Enum[LazyRef(...)]](using ctag: ClassTag[T]): ConfigDelegate[T]","d":"little/config","k":"given"},
{"l":"little/config.html","n":"fileDelegate","t":"given fileDelegate: fileDelegate.type","d":"little/config","k":"given"},
{"l":"little/config.html","n":"intDelegate","t":"given intDelegate: intDelegate.type","d":"little/config","k":"given"},
{"l":"little/config.html","n":"longDelegate","t":"given longDelegate: longDelegate.type","d":"little/config","k":"given"},
{"l":"little/config.html","n":"memorySizeDelegate","t":"given memorySizeDelegate: memorySizeDelegate.type","d":"little/config","k":"given"},
{"l":"little/config.html","n":"periodDelegate","t":"given periodDelegate: periodDelegate.type","d":"little/config","k":"given"},
{"l":"little/config.html","n":"stringDelegate","t":"given stringDelegate: stringDelegate.type","d":"little/config","k":"given"},
{"l":"little/config/ConfigDelegate.html","n":"ConfigDelegate","t":"trait ConfigDelegate[T]","d":"little/config/ConfigDelegate","k":"trait"},
{"l":"little/config/ConfigDelegate.html","n":"get","t":"def get(config: Config, path: String): T","d":"little/config/ConfigDelegate","k":"def"},
{"l":"little/config/ConfigMethods.html","n":"ConfigMethods","t":"class ConfigMethods(config: Config) extends AnyVal","d":"little/config/ConfigMethods","k":"class"},
{"l":"little/config/ConfigMethods.html","n":"get","t":"def get[T](path: String)(using delegate: ConfigDelegate[T]): T","d":"little/config/ConfigMethods","k":"def"},
{"l":"little/config/ConfigMethods.html","n":"getFile","t":"def getFile(path: String): File","d":"little/config/ConfigMethods","k":"def"},
{"l":"little/config/ConfigMethods.html","n":"getFileList","t":"def getFileList(path: String): List[File]","d":"little/config/ConfigMethods","k":"def"},
{"l":"little/config/ConfigMethods.html","n":"getOption","t":"def getOption[T](path: String)(using delegate: ConfigDelegate[T]): Option[T]","d":"little/config/ConfigMethods","k":"def"},
{"l":"little/config/ConfigMethods.html","n":"getOrElse","t":"def getOrElse[T](path: String, default: => T)(using delegate: ConfigDelegate[T]): T","d":"little/config/ConfigMethods","k":"def"},
{"l":"little/config/ConfigMethods.html","n":"getTry","t":"def getTry[T](path: String)(using delegate: ConfigDelegate[T]): Try[T]","d":"little/config/ConfigMethods","k":"def"},
{"l":"little/config/booleanDelegate$.html","n":"booleanDelegate","t":"object booleanDelegate extends ConfigDelegate[Boolean]","d":"little/config/booleanDelegate$","k":"object"},
{"l":"little/config/booleanDelegate$.html","n":"get","t":"def get(config: Config, path: String): Boolean","d":"little/config/booleanDelegate$","k":"def"},
{"l":"little/config/configDelegate$.html","n":"configDelegate","t":"object configDelegate extends ConfigDelegate[Config]","d":"little/config/configDelegate$","k":"object"},
{"l":"little/config/configDelegate$.html","n":"get","t":"def get(config: Config, path: String): Config","d":"little/config/configDelegate$","k":"def"},
{"l":"little/config/doubleDelegate$.html","n":"doubleDelegate","t":"object doubleDelegate extends ConfigDelegate[Double]","d":"little/config/doubleDelegate$","k":"object"},
{"l":"little/config/doubleDelegate$.html","n":"get","t":"def get(config: Config, path: String): Double","d":"little/config/doubleDelegate$","k":"def"},
{"l":"little/config/durationDelegate$.html","n":"durationDelegate","t":"object durationDelegate extends ConfigDelegate[Duration]","d":"little/config/durationDelegate$","k":"object"},
{"l":"little/config/durationDelegate$.html","n":"get","t":"def get(config: Config, path: String): Duration","d":"little/config/durationDelegate$","k":"def"},
{"l":"little/config/fileDelegate$.html","n":"fileDelegate","t":"object fileDelegate extends ConfigDelegate[File]","d":"little/config/fileDelegate$","k":"object"},
{"l":"little/config/fileDelegate$.html","n":"get","t":"def get(config: Config, path: String): File","d":"little/config/fileDelegate$","k":"def"},
{"l":"little/config/intDelegate$.html","n":"intDelegate","t":"object intDelegate extends ConfigDelegate[Int]","d":"little/config/intDelegate$","k":"object"},
{"l":"little/config/intDelegate$.html","n":"get","t":"def get(config: Config, path: String): Int","d":"little/config/intDelegate$","k":"def"},
{"l":"little/config/longDelegate$.html","n":"longDelegate","t":"object longDelegate extends ConfigDelegate[Long]","d":"little/config/longDelegate$","k":"object"},
{"l":"little/config/longDelegate$.html","n":"get","t":"def get(config: Config, path: String): Long","d":"little/config/longDelegate$","k":"def"},
{"l":"little/config/memorySizeDelegate$.html","n":"memorySizeDelegate","t":"object memorySizeDelegate extends ConfigDelegate[ConfigMemorySize]","d":"little/config/memorySizeDelegate$","k":"object"},
{"l":"little/config/memorySizeDelegate$.html","n":"get","t":"def get(config: Config, path: String): ConfigMemorySize","d":"little/config/memorySizeDelegate$","k":"def"},
{"l":"little/config/periodDelegate$.html","n":"periodDelegate","t":"object periodDelegate extends ConfigDelegate[Period]","d":"little/config/periodDelegate$","k":"object"},
{"l":"little/config/periodDelegate$.html","n":"get","t":"def get(config: Config, path: String): Period","d":"little/config/periodDelegate$","k":"def"},
{"l":"little/config/stringDelegate$.html","n":"stringDelegate","t":"object stringDelegate extends ConfigDelegate[String]","d":"little/config/stringDelegate$","k":"object"},
{"l":"little/config/stringDelegate$.html","n":"get","t":"def get(config: Config, path: String): String","d":"little/config/stringDelegate$","k":"def"},
{"l":"docs/index.html","n":"little-config","t":"little-config","d":"","k":"static"}];